namespace ClearBlazor
{
    public static class ColourNames
    {
        public static List<ColourName> Names = new List<ColourName>
            {
                new ColourName {Name = "aliceblue",Value="#f0f8ff"},
                new ColourName {Name = "antiquewhite",Value="#faebd7"},
                new ColourName {Name = "aqua",Value="#00ffff"},
                new ColourName {Name = "aquamarine",Value="#7fffd4"},
                new ColourName {Name = "azure",Value="#f0ffff"},
                new ColourName {Name = "beige",Value="#f5f5dc"},
                new ColourName {Name = "bisque",Value="#ffe4c4"},
                new ColourName {Name = "black",Value="#000000"},
                new ColourName {Name = "blanchedalmond",Value="#ffebcd"},
                new ColourName {Name = "blue",Value="#0000ff"},
                new ColourName {Name = "blueviolet",Value="#8a2be2"},
                new ColourName {Name = "brown",Value="#a52a2a"},
                new ColourName {Name = "burlywood",Value="#deb887"},
                new ColourName {Name = "cadetblue",Value="#5f9ea0"},
                new ColourName {Name = "chartreuse",Value="#7fff00"},
                new ColourName {Name = "chocolate",Value="#d2691e"},
                new ColourName {Name = "coral",Value="#ff7f50"},
                new ColourName {Name = "cornflowerblue",Value="#6495ed"},
                new ColourName {Name = "cornsilk",Value="#fff8dc"},
                new ColourName {Name = "crimson",Value="#dc143c"},
                new ColourName {Name = "cyan",Value="#00ffff"},
                new ColourName {Name = "darkblue",Value="#00008b"},
                new ColourName {Name = "darkcyan",Value="#008b8b"},
                new ColourName {Name = "darkgoldenrod",Value="#b8860b"},
                new ColourName {Name = "darkgray",Value="#a9a9a9"},
                new ColourName {Name = "darkgrey",Value="#a9a9a9"},
                new ColourName {Name = "darkgreen",Value="#006400"},
                new ColourName {Name = "darkkhaki",Value="#bdb76b"},
                new ColourName {Name = "darkmagenta",Value="#8b008b"},
                new ColourName {Name = "darkolivegreen",Value="#556b2f"},
                new ColourName {Name = "darkorange",Value="#ff8c00"},
                new ColourName {Name = "darkorchid",Value="#9932cc"},
                new ColourName {Name = "darkred",Value="#8b0000"},
                new ColourName {Name = "darksalmon",Value="#e9967a"},
                new ColourName {Name = "darkseagreen",Value="#8fbc8f"},
                new ColourName {Name = "darkslateblue",Value="#483d8b"},
                new ColourName {Name = "darkslategray",Value="#2f4f4f"},
                new ColourName {Name = "darkslategrey",Value="#2f4f4f"},
                new ColourName {Name = "darkturquoise",Value="#00ced1"},
                new ColourName {Name = "darkviolet",Value="#9400d3"},
                new ColourName {Name = "deeppink",Value="#ff1493"},
                new ColourName {Name = "deepskyblue",Value="#00bfff"},
                new ColourName {Name = "dimgray",Value="#696969"},
                new ColourName {Name = "dimgrey",Value="#696969"},
                new ColourName {Name = "dodgerblue",Value="#1e90ff"},
                new ColourName {Name = "firebrick",Value="#b22222"},
                new ColourName {Name = "floralwhite",Value="#fffaf0"},
                new ColourName {Name = "forestgreen",Value="#228b22"},
                new ColourName {Name = "fuchsia",Value="#ff00ff"},
                new ColourName {Name = "gainsboro",Value="#dcdcdc"},
                new ColourName {Name = "ghostwhite",Value="#f8f8ff"},
                new ColourName {Name = "gold",Value="#ffd700"},
                new ColourName {Name = "goldenrod",Value="#daa520"},
                new ColourName {Name = "gray",Value="#808080"},
                new ColourName {Name = "grey",Value="#808080"},
                new ColourName {Name = "green",Value="#008000"},
                new ColourName {Name = "greenyellow",Value="#adff2f"},
                new ColourName {Name = "honeydew",Value="#f0fff0"},
                new ColourName {Name = "hotpink",Value="#ff69b4"},
                new ColourName {Name = "indianred",Value="#cd5c5c"},
                new ColourName {Name = "indigo",Value="#4b0082"},
                new ColourName {Name = "ivory",Value="#fffff0"},
                new ColourName {Name = "khaki",Value="#f0e68c"},
                new ColourName {Name = "lavender",Value="#e6e6fa"},
                new ColourName {Name = "lavenderblush",Value="#fff0f5"},
                new ColourName {Name = "lawngreen",Value="#7cfc00"},
                new ColourName {Name = "lemonchiffon",Value="#fffacd"},
                new ColourName {Name = "lightblue",Value="#add8e6"},
                new ColourName {Name = "lightcoral",Value="#f08080"},
                new ColourName {Name = "lightcyan",Value="#e0ffff"},
                new ColourName {Name = "lightgoldenrodyellow",Value="#fafad2"},
                new ColourName {Name = "lightgray",Value="#d3d3d3"},
                new ColourName {Name = "lightgrey",Value="#d3d3d3"},
                new ColourName {Name = "lightgreen",Value="#90ee90"},
                new ColourName {Name = "lightpink",Value="#ffb6c1"},
                new ColourName {Name = "lightsalmon",Value="#ffa07a"},
                new ColourName {Name = "lightseagreen",Value="#20b2aa"},
                new ColourName {Name = "lightskyblue",Value="#87cefa"},
                new ColourName {Name = "lightslategray",Value="#778899"},
                new ColourName {Name = "lightslategrey",Value="#778899"},
                new ColourName {Name = "lightsteelblue",Value="#b0c4de"},
                new ColourName {Name = "lightyellow",Value="#ffffe0"},
                new ColourName {Name = "lime",Value="#00ff00"},
                new ColourName {Name = "limegreen",Value="#32cd32"},
                new ColourName {Name = "linen",Value="#faf0e6"},
                new ColourName {Name = "magenta",Value="#ff00ff"},
                new ColourName {Name = "maroon",Value="#800000"},
                new ColourName {Name = "mediumaquamarine",Value="#66cdaa"},
                new ColourName {Name = "mediumblue",Value="#0000cd"},
                new ColourName {Name = "mediumorchid",Value="#ba55d3"},
                new ColourName {Name = "mediumpurple",Value="#9370d8"},
                new ColourName {Name = "mediumseagreen",Value="#3cb371"},
                new ColourName {Name = "mediumslateblue",Value="#7b68ee"},
                new ColourName {Name = "mediumspringgreen",Value="#00fa9a"},
                new ColourName {Name = "mediumturquoise",Value="#48d1cc"},
                new ColourName {Name = "mediumvioletred",Value="#c71585"},
                new ColourName {Name = "midnightblue",Value="#191970"},
                new ColourName {Name = "mintcream",Value="#f5fffa"},
                new ColourName {Name = "mistyrose",Value="#ffe4e1"},
                new ColourName {Name = "moccasin",Value="#ffe4b5"},
                new ColourName {Name = "navajowhite",Value="#ffdead"},
                new ColourName {Name = "navy",Value="#000080"},
                new ColourName {Name = "oldlace",Value="#fdf5e6"},
                new ColourName {Name = "olive",Value="#808000"},
                new ColourName {Name = "olivedrab",Value="#6b8e23"},
                new ColourName {Name = "orange",Value="#ffa500"},
                new ColourName {Name = "orangered",Value="#ff4500"},
                new ColourName {Name = "orchid",Value="#da70d6"},
                new ColourName {Name = "palegoldenrod",Value="#eee8aa"},
                new ColourName {Name = "palegreen",Value="#98fb98"},
                new ColourName {Name = "paleturquoise",Value="#afeeee"},
                new ColourName {Name = "palevioletred",Value="#d87093"},
                new ColourName {Name = "papayawhip",Value="#ffefd5"},
                new ColourName {Name = "peachpuff",Value="#ffdab9"},
                new ColourName {Name = "peru",Value="#cd853f"},
                new ColourName {Name = "pink",Value="#ffc0cb"},
                new ColourName {Name = "plum",Value="#dda0dd"},
                new ColourName {Name = "powderblue",Value="#b0e0e6"},
                new ColourName {Name = "purple",Value="#800080"},
                new ColourName {Name = "red",Value="#ff0000"},
                new ColourName {Name = "rosybrown",Value="#bc8f8f"},
                new ColourName {Name = "royalblue",Value="#4169e1"},
                new ColourName {Name = "saddlebrown",Value="#8b4513"},
                new ColourName {Name = "salmon",Value="#fa8072"},
                new ColourName {Name = "sandybrown",Value="#f4a460"},
                new ColourName {Name = "seagreen",Value="#2e8b57"},
                new ColourName {Name = "seashell",Value="#fff5ee"},
                new ColourName {Name = "sienna",Value="#a0522d"},
                new ColourName {Name = "silver",Value="#c0c0c0"},
                new ColourName {Name = "skyblue",Value="#87ceeb"},
                new ColourName {Name = "slateblue",Value="#6a5acd"},
                new ColourName {Name = "slategray",Value="#708090"},
                new ColourName {Name = "slategrey",Value="#708090"},
                new ColourName {Name = "snow",Value="#fffafa"},
                new ColourName {Name = "springgreen",Value="#00ff7f"},
                new ColourName {Name = "steelblue",Value="#4682b4"},
                new ColourName {Name = "tan",Value="#d2b48c"},
                new ColourName {Name = "teal",Value="#008080"},
                new ColourName {Name = "thistle",Value="#d8bfd8"},
                new ColourName {Name = "tomato",Value="#ff6347"},
                new ColourName {Name = "turquoise",Value="#40e0d0"},
                new ColourName {Name = "violet",Value="#ee82ee"},
                new ColourName {Name = "wheat",Value="#f5deb3"},
                new ColourName {Name = "white",Value="#ffffff"},
                new ColourName {Name = "whitesmoke",Value="#f5f5f5"},
                new ColourName {Name = "yellow",Value="#ffff00"},
                new ColourName {Name = "yellowgreen",Value="#9acd32"}
        };

        public static string GetRgbForColourName(string name)
        {
            var name1 = Names.FirstOrDefault(n => n.Name == name);
            if (name1 == null)
                return "#000000";
            return name1.Value;
        }
    }

    

    public class ColourName
    {
        public string Name { get; set; }
        public string Value { get; set; }
    }
}
