name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

permissions:
  contents: read
  pull-requests: write 

jobs:
  build_and_deploy_job:
    if: (github.event_name == 'push' && startsWith(github.event.commits[0].message, 'Version Package')) || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: setup-dotnet
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: src/global.json
          
      - name: dotnet workload restore
        run: dotnet workload restore src/ClearBlazorTest.sln
        
      - name: Build Solution
        run: dotnet build src/ClearBlazorTest.sln --configuration Release
        
      - name: Publish Web Test Project
        run: dotnet publish src/ClearBlazorTest.Web/ClearBlazorTest.Web.csproj --configuration Release
      
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BRAVE_SKY_0982BFC10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "src/ClearBlazorTest.Web/bin/Release/net9.0/publish/wwwroot"
          skip_app_build: true
          is_static_export: true
          output_location: "wwwroot"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BRAVE_SKY_0982BFC10 }}
          action: "close"
          app_location: "" #not required for close, but causes IDE errors if it's left out.
