name: Version Package 

on:
  push:
    branches:
    - main
    
jobs:
  build-and-publish:
    if: ${{ startsWith(github.event.commits[0].message, 'Version Package') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - name: Get Version
        id: get-version
        run: |
          version=$(jq -r .version package.json)
          echo "versionToPublish=$version" >> $GITHUB_OUTPUT

      - name: Build Nuget Package
        run: dotnet pack src/ClearBlazor/ClearBlazor.csproj --configuration Release

      - name: Create Release
        uses: changesets/action@v1
        with:
          publish: "npx @changesets/cli tag"
          createGitHubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Nuget Package to Github Release
        run: |
          gh release upload ${{ steps.get-version.outputs.versionToPublish }} "src/ClearBlazor/bin/Release/ClearBlazor.${{ steps.get-version.outputs.versionToPublish }}.nupkg"

      - name: Publish to Nuget
        run: |
          echo "TODO publish to nuget package: ClearBlazor.${{ steps.get-version.outputs.versionToPublish }}.nupkg"





