name: Create or Update Versioning PR 

on:
  push:
    branches:
    - main

permissions:
  contents: write
  pull-requests: write 

jobs:
  version:
    runs-on: ubuntu-latest

    # For all pushes that aren't creating a versioning commit
    if: ${{ !startsWith(github.event.commits[0].message, 'Version Package') }}
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: setup-node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Cache .pnpm-store
      uses: actions/cache@v3.2.3
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}

    - uses: pnpm/action-setup@v4
      with:
        version: 8.15.2
        run_install: true

    - name: Install YQ
      uses: dcarbone/install-yq-action@v1.1.1

    - name: Create Release Pull Request
      id: changesets
      uses: changesets/action@v1
      with:
        commit: 'Version Package'
        title: 'Version Package'
        createGitHubReleases: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: 'Update version in Octopus Deploy Chart.yaml'
      run: |
        version=$(jq -r .version src/ClearBlazor/package.json)
        sed -i '' "s/\(<Version>\).*\(<\/Version>\)/\1$version\2/" src/ClearBlazor/ClearBlazor.csproj
        sed -i '' "s/\(<AssemblyVersion>\).*\(<\/AssemblyVersion>\)/\1$version\2/" src/ClearBlazor/ClearBlazor.csproj
        sed -i '' "s/\(<FileVersion>\).*\(<\/FileVersion>\)/\1$version\2/" src/ClearBlazor/ClearBlazor.csproj
        git config user.email "action@github.com"
        git config user.name "github-actions[bot]"
        git add src/ClearBlazor/ClearBlazor.csproj
        git commit -m "Update package version in ClearBlazor.csproj"
      if: steps.changesets.outputs.hasChangesets == 'true'

    - name: 'Push changes'
      run: |
        git push --set-upstream origin changeset-release/main
      if: steps.changesets.outputs.hasChangesets == 'true'